spring.application.name=Interactive_map_Ostrava

# Nastavení p?ipojení k PostgreSQL v Dockeru
spring.datasource.url=jdbc:postgresql://localhost:5432/ostrava_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate nastavení
# create-drop: p?i ka?dém startu sma?e a znovu vytvo?í tabulky (super pro vývoj)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

# Klí?ové nastavení pro prostorová data (PostGIS)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect